version: "3.3"

services:
  peertube:

    build: .
    image: peertube:stretch
    environment:
      PEERTUBE_HOSTNAME: my.domain.tld
      PEERTUBE_PORT: 443
      PEERTUBE_HTTPS: true
      PEERTUBE_ADMIN_EMAIL: admin@domain.tld
      PEERTUBE_DB_USERNAME: user
      PEERTUBE_DB_PASSWORD: password
      PEERTUBE_SIGNUP_ENABLED: true
      PEERTUBE_TRANSCODING_ENABLED: true
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:${PEERTUBE_HOSTNAME}"
      traefik.port: "9000"
    volumes:
      - ./data:/usr/src/app/data
    depends_on:
      - db

  db:
    image: postgres:10
    environment:
      POSTGRES_USERNAME: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: peertube_prod
    volumes:
      - ./db:/var/lib/postgresql/data
