blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ IRC
    url: https://kiwiirc.com/client/irc.freenode.net/#peertube
    about: Chat with us via IRC for quick Q/A here
  - name: ğŸ’¬ Matrix
    url: https://matrix.to/#/#peertube:matrix.org
    about: Chat with us via Matrix for quick Q/A here
  - name: ğŸ¤·ğŸ’»ğŸ¤¦ Forum
    url: https://framacolibri.org/c/peertube
    about: You can ask and answer other questions here
