listen:
  port: 9003

webserver:
  port: 9003

database:
  suffix: '_test3'

# From the project root directory
storage:
  tmp: 'test3/tmp/'
  tmp_persistent: 'test3/tmp-persistent/'
  bin: 'test3/bin/'
  avatars: 'test3/avatars/'
  web_videos: 'test3/web-videos/'
  streaming_playlists: 'test3/streaming-playlists/'
  original_video_files: 'test3/original-video-files/'
  redundancy: 'test3/redundancy/'
  logs: 'test3/logs/'
  previews: 'test3/previews/'
  thumbnails: 'test3/thumbnails/'
  storyboards: 'test3/storyboards/'
  torrents: 'test3/torrents/'
  captions: 'test3/captions/'
  cache: 'test3/cache/'
  plugins: 'test3/plugins/'
  well_known: 'test3/well-known/'
  client_overrides: 'test3/client-overrides/'

admin:
  email: 'admin3@example.com'

transcoding:
  enabled: false

video_studio:
  enabled: false
