listen:
  hostname: '0.0.0.0'
  port: 9000

webserver:
  https: false

database:
  hostname: 'localhost'
  port: 5432

smtp:
  hostname: null
  port: 1025
  tls: false
  disable_starttls: true
  from_address: 'test-admin@localhost'
  username: null
  password: null

log:
  level: 'debug'

contact_form:
  enabled: true

redundancy:
  videos:
    check_interval: '10 minutes'
    strategies:
      -
        size: '10MB'
        min_lifetime: '10 minutes'
        strategy: 'most-views'
      -
        size: '10MB'
        min_lifetime: '10 minutes'
        strategy: 'trending'
      -
        size: '10MB'
        min_lifetime: '10 minutes'
        strategy: 'recently-added'
        min_views: 1

cache:
  previews:
    size: 1
  captions:
    size: 1

signup:
  enabled: true
  requires_email_verification: false

transcoding:
  enabled: true
  allow_additional_extensions: false
  threads: 2
  resolutions:
    240p: true
    360p: true
    480p: true
    720p: true
    1080p: true
  hls:
    enabled: true

import:
  videos:
    http:
      enabled: true
    torrent:
      enabled: true

instance:
  default_nsfw_policy: 'display'
