listen:
  port: 9005

webserver:
  hostname: 'localhost'
  port: 9005

database:
  suffix: '_test5'

# From the project root directory
storage:
  tmp: 'test5/tmp/'
  avatars: 'test5/avatars/'
  videos: 'test5/videos/'
  playlists: 'test5/playlists/'
  redundancy: 'test5/redundancy/'
  logs: 'test5/logs/'
  previews: 'test5/previews/'
  thumbnails: 'test5/thumbnails/'
  torrents: 'test5/torrents/'
  captions: 'test5/captions/'
  cache: 'test5/cache/'

admin:
  email: 'admin5@example.com'

transcoding:
  enabled: false
