listen:
  hostname: '0.0.0.0'
  port: 9000

webserver:
  https: false

rates_limit:
  signup:
    window: 10 minutes
    max: 50
  login:
    window: 5 minutes
    max: 20
  api:
    window: 10 seconds
    max: 500

database:
  hostname: 'localhost'
  port: 5432

redis:
  hostname: 'localhost'

smtp:
  hostname: null
  port: 1025
  tls: false
  disable_starttls: true
  from_address: 'test-admin@localhost'
  username: null
  password: null

log:
  level: 'debug'

contact_form:
  enabled: true

redundancy:
  videos:
    check_interval: '1 minute'
    strategies:
      -
        size: '1000MB'
        min_lifetime: '10 minutes'
        strategy: 'most-views'
      -
        size: '1000MB'
        min_lifetime: '10 minutes'
        strategy: 'trending'
      -
        size: '1000MB'
        min_lifetime: '10 minutes'
        strategy: 'recently-added'
        min_views: 1

cache:
  previews:
    size: 1
  captions:
    size: 1

signup:
  enabled: true
  requires_email_verification: false

transcoding:
  enabled: true
  allow_additional_extensions: false
  allow_audio_files: false
  threads: 2
  resolutions:
    0p: false
    240p: true
    360p: true
    480p: true
    720p: true
    1080p: true
    2160p: true
  hls:
    enabled: true

import:
  videos:
    http:
      enabled: true
      proxy:
        enabled: false
        url: ""
    torrent:
      enabled: true

instance:
  default_nsfw_policy: 'display'

plugins:
  index:
    check_latest_versions_interval: '10 minutes'
