listen:
  port: 9004

webserver:
  hostname: 'localhost'
  port: 9004

database:
  suffix: '_test4'

# From the project root directory
storage:
  tmp: 'test4/tmp/'
  avatars: 'test4/avatars/'
  videos: 'test4/videos/'
  playlists: 'test4/playlists/'
  redundancy: 'test4/redundancy/'
  logs: 'test4/logs/'
  previews: 'test4/previews/'
  thumbnails: 'test4/thumbnails/'
  torrents: 'test4/torrents/'
  captions: 'test4/captions/'
  cache: 'test4/cache/'

admin:
  email: 'admin4@example.com'

transcoding:
  enabled: false
