listen:
  port: 9006

webserver:
  hostname: 'localhost'
  port: 9006

database:
  suffix: '_test6'

# From the project root directory
storage:
  tmp: 'test6/tmp/'
  avatars: 'test6/avatars/'
  videos: 'test6/videos/'
  playlists: 'test6/playlists/'
  redundancy: 'test6/redundancy/'
  logs: 'test6/logs/'
  previews: 'test6/previews/'
  thumbnails: 'test6/thumbnails/'
  torrents: 'test6/torrents/'
  captions: 'test6/captions/'
  cache: 'test6/cache/'

admin:
  email: 'admin6@example.com'

transcoding:
  enabled: false
