listen:
  port: 9006

webserver:
  port: 9006

database:
  suffix: '_test6'

# From the project root directory
storage:
  tmp: 'test6/tmp/'
  tmp_persistent: 'test6/tmp-persistent/'
  bin: 'test6/bin/'
  avatars: 'test6/avatars/'
  web_videos: 'test6/web-videos/'
  streaming_playlists: 'test6/streaming-playlists/'
  original_video_files: 'test6/original-video-files/'
  redundancy: 'test6/redundancy/'
  logs: 'test6/logs/'
  previews: 'test6/previews/'
  thumbnails: 'test6/thumbnails/'
  storyboards: 'test6/storyboards/'
  torrents: 'test6/torrents/'
  captions: 'test6/captions/'
  cache: 'test6/cache/'
  plugins: 'test6/plugins/'
  well_known: 'test6/well-known/'
  client_overrides: 'test6/client-overrides/'

admin:
  email: 'admin6@example.com'

transcoding:
  enabled: false

video_studio:
  enabled: false
