listen:
  port: 9001

webserver:
  hostname: 'localhost'
  port: 9001

database:
  suffix: '_test1'

# From the project root directory
storage:
  tmp: 'test1/tmp/'
  avatars: 'test1/avatars/'
  videos: 'test1/videos/'
  playlists: 'test1/playlists/'
  redundancy: 'test1/redundancy/'
  logs: 'test1/logs/'
  previews: 'test1/previews/'
  thumbnails: 'test1/thumbnails/'
  torrents: 'test1/torrents/'
  captions: 'test1/captions/'
  cache: 'test1/cache/'

admin:
  email: 'admin1@example.com'

user:
  video_quota: 5242880 # 5MB

signup:
  limit: 4

transcoding:
  enabled: false
